openapi: 3.0.4
info:
  version: '1.0'
  title: "RenTrento OpenAPI 1.0"
  description: API for renting any montain materials.

servers:
  - url: http://localhost:8080/renTrentoAPI
    description: Localhost

tags:
  - name: Authentication
  - name: Users
  - name: Products
  - name: Rentals
  - name: Categories

paths:
  /authentications:
    post:
      summary: Authenticate a user
      description: >-
        Authenticates a user and returns a JWT 'token'.
      responses:
        '200':
          description: 'Token created'
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    description: 'True if the authentication was successful'
                  token:
                    type: string
                    description: 'JWT token'
        '401':
          description: 'Unauthorized. Invalid credentials'
      requestBody:
        description: >-
          The email and password must be passed in the body.
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  description: 'Email address of the user'
                password:
                  type: string
                  description: 'Password of the user'


  /users:
    get:
      tags:
        - Users
      description: Gets the list of users.
      summary: 'View all users'
      responses: 
        '200':
          description: list of users 
          content: 
            application/json:
              schema: 
                type: array
                items: 
                  $ref: '#/components/schemas/User'

    post:
      tags:
        - Users
      description: Creates a new user account
      summary: 'Add a new user'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '201':
          description: 'User created'
          content: 
            application/json:
              schema:
                $ref: '#/components/schemas/User'

  /users/{userId}:
    get:
      tags:
        - Users
      description: Get details of the profile of the user by their ID
      summary: 'View a user'
      parameters:
        - in: path
          name: userId
          required: true
          schema:
            type: string
          description: ID of the user
      responses:
        '200':
          description: User found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'

        '404':
          description: User not found

    delete:
      tags:
        - Users
      description: Delete a book with the given ID
      summary: 'Delete a user'
      parameters:
        - in: path
          name: userId
          required: true
          schema:
            type: string
          description: 'ID of the user'
      responses:
        '204':
          description: 'User deleted'
        '404':
          description: 'User not found'
    
    patch:
      tags:
        - Users
      description: Updates specific fields of a user
      summary: 'Update a user'
      parameters:
        - in: path
          name: userId
          required: true
          schema:
            type: string
          description: 'ID of the user'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email: 
                  type: string
                password:
                  type: string
                wallet:
                  type: number
      responses:
        '200':
          description: 'User updated'
        '404':
          description: 'User not found'
        

  /products:
    get:
      tags:
        - Products
      description: >-
        Get the list of products.
        It possible to show products by the user that posted them, by their category or by their status
      summary: View all products
      parameters:
        - in: query
          name: productUserId
          schema:
            type: string
        - in: query
          name: category
          schema:
            type: string
        - in: query
          name: status
          schema:
            type: string
            enum: [available, unavailable, rented]
      responses:
        '200':
          description: 'Collection of users'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'

    post:
      tags:
        - Products
      description: Creates a new product in the system
      summary: Add a new product
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
      responses:
        '201':
          description: 'Product created'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'


  /products/{productId}:
    get:
      tags:
        - Products
      description: Gets the product with the given ID.
      summary: View a product
      parameters:
        - in: path
          name: productId
          required: true
          schema:
            type: string
          description: 'ID of the product'
      responses:
        '200':
          description: 'Book found'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        '404':
          description: 'Product not found'

    delete:
      tags:
        - Products
      description: Deletes the product with the given ID
      summary: Delete a product
      parameters:
        - in: path
          name: productId
          required: true
          schema:
            type: string
          description: "ID of the product"
      responses:
        '204':
          description: 'Product deleted'
        '404':
          description: 'Book not found'

    patch:
      tags:
        - Products
      description: Updates specific fields of a product
      summary: 'Update a product'
      parameters:
        - in: path
          name: productId
          required: true
          schema:
            type: string
            description: 'ID of the product'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                productUserName:
                  type: string
                productName:
                  type: string
                category:
                  type: string
                productInfo:
                  type: string
                productPrice:
                  type: number
                status:
                  type: string
                  enum: [available, unavailable, rented]
      responses:
        '200':
          description: 'Product updated'
        '404':
          description: 'Product not found'
        

  /rentals:
    get:
      tags:
        - Rentals
      description: >-
        Get the list of rentals.
        It is possible to show rentals by the product, the renter, the client, the start date, the end date or the status
      summary: View all rentals
      parameters:
        - in: query
          name: productId
          schema:
            type: string
        - in: query
          name: renterId
          schema:
            type: string
        - in: query
          name: clientId
          schema:
            type: string
        - in: query
          name: startDate
          schema:
            type: string
            format: date-time
        - in: query
          name: endDate
          schema:
            type: string
            format: date-time
        - in: query
          name: status
          schema:
            type: string
            enum: [active,not_active,finished]
      responses:
        '200':
          description: 'Collection of rentals'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Rental'
    
    post:
      tags:
        - Rentals
      description: Creates a new rental in the system
      summary: Add a new rental
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Rental'
      responses:
        '201':
          description: 'Rental created'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Rental'

          
  /rentals/{rentalId}:
    get:
      tags:
        - Rentals
      description: Gets the rental with the given ID.
      summary: View a rental
      parameters:
        - in: path
          name: rentalId
          required: true
          schema:
            type: string
          description: 'ID of the rental'
      responses:
        '200':
          description: 'rental found'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Rental'
        '404':
          description: 'Rental not found'

    delete:
      tags:
        - Rentals
      description: Deletes the rental with the given ID
      summary: Delete a rental
      parameters:
        - in: path
          name: rentalId
          required: true
          schema:
            type: string
          description: "ID of the rental"
      responses:
        '204':
          description: 'Rental deleted'
        '404':
          description: 'Rental not found'

    patch:
      tags:
        - Rentals
      description: Updates specific fields of a rental
      summary: 'Update a rental'
      parameters:
        - in: path
          name: rentalId
          required: true
          schema:
            type: string
            description: 'ID of the rental'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                startDate:
                  type: string
                  format: date-time
                  description: 'Start date of the rental'
                endDate:
                  type: string
                  format: date-time
                  description: 'End date of the rental'
                rentalPrice:
                  type: number
                  description: 'Price of the rental'
                status:
                  type: string
                  enum: [active,not_active,finished]
      responses:
        '200':
          description: 'Rental updated'
        '404':
          description: 'Rental not found'


  /categories:
    get:
      tags:
        - Categories
      description: Get the list of the product categories
      summary: View all categories
      parameters:
        - in: query
          name: categoryId
          schema:
            type: string
        - in: query
          name: categoryName
          schema:
            type: string
      responses:
        '200':
          description: 'Collection of categories'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Category'

    post:
      tags:
        - Categories
      description: Creates a new product category in the system
      summary: Add a new product category
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Category'
      responses:
        '201':
          description: 'Category created'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Category'

    
  /categories/{categoryId}:
    delete:
      tags:
        - Categories
      description: Deletes the category with the given ID
      summary: Delete a category
      parameters:
        - in: path
          name: categoryId
          required: true
          schema:
            type: string
          description: 'ID of the category'
      responses:
        '204':
          description: 'Category deleted'
        '404':
          description: 'Category not found'

###########################################################################

components: 
  schemas:
    User:  
        type: object
        required:
          #- userId
          - userName
          - role 
          - email
          - password
          - wallet
        properties: 
          self: 
            type: string
            description: 'Link to the user'
          #userId:
           # type: string
            #description: 'ID of the user'
          userName:
            type: string
            description: 'Username of the account'
          role:
            type: string
            enum: [user, admin]
            description: 'Role of the user'
          email: 
            type: string
            description: 'Email address of the user'
          password:
            type: string
            description: 'password of the user'
          wallet:
            type: number
            description: 'wallet of the user'

    Product:
      type: object
      required:
        #- productId
        - productUserId
        - productUserName
        - productName
        - category
        - productInfo
        - productPrice
        - status
      properties:
        self: 
          type: string
          description: 'Link to the product'
        #productId:
         # type: string
          #description: 'ID of the product'
        productUserId:
          type: string
          description: 'ID of the user that posted the product'
        productUserName:
          type: string
          description: 'Name of the user that posted the product'
        productName:
          type: string
          description: 'Name of the product'
        category:
          type: string
        productInfo:
          type: string
          description: 'Description of the product'
        productPrice:
          type: number
          description: 'Price of the product'
        status:
          type: string
          enum: [available, unavailable, rented]
          description: 'Status of the product'

    Rental:
      type: object
      required: 
        #- rentalId
        - productId
        - renterId
        - clientId
        - startDate
        - endDate
        - rentalPrice
        - status
      properties:
        self:
          type: string
          description: 'Link to the rental'
        #rentalId:
         # type: string
          #description: 'ID of the rental'
        productId:
          type: string
          description: 'ID of the product'
        renterId:
          type: string
          description: 'ID of the renter'
        clientId:
          type: string
          description: 'ID of the client'
        startDate:
          type: string
          format: date-time
          description: 'Start date of the rental'
        endDate:
          type: string
          format: date-time
          description: 'End date of the rental'
        rentalPrice:
          type: number
          description: 'Price of the rental'
        status:
          type: string
          enum: [active,not_active,finished]
          description: 'Tells if the rental is active, will be active in the future (not_active) or finished'

    Category:
      type: object
      required:
        #- categoryId
        - categoryName
      properties:
        self:
          type: string
          description: 'link to the category'
        #categoryId:
         # type: string
          #description: 'ID of the category'
        categoryName:
          type: string
          description: 'Name of the category'


